Ws 019 admin endpoint
TimLeach635/WhaleSpotting-OpenCohort2023 pull request #35
Opened 2023-11-08 14:29 UTC by mtharkins

Add boolean to Sighting model & endpoint to Admin controller for unapproved sightings

2023-11-08 16:00 UTC, mtharkins commented
Sorry I had missed the merge conflict previously, it's been resolved now and is ready for review.

2023-11-09 12:16 UTC, AndrewYHuang requested changes
Just one small change, then it should be ready to merge in!

2023-11-09 12:16 UTC, AndrewYHuang commented on WhaleSpotting/Controllers/AdminController.cs
> +using SQLitePCL;
Probably want to remove this

2023-11-09 12:16 UTC, AndrewYHuang commented on WhaleSpotting/Controllers/AdminController.cs
> +using SQLitePCL;
```suggestion
```

2023-11-09 12:19 UTC, AndrewYHuang approved these changes

2023-11-09 12:19 UTC, merged