Ws 031 get involved page
TimLeach635/WhaleSpotting-OpenCohort2023 pull request #37
Opened 2023-11-08 14:51 UTC by DeanErickson

2023-11-08 15:53 UTC, TimLeach635 requested changes

2023-11-08 15:53 UTC, TimLeach635 commented on WhaleSpotting/Views/Home/GetInvolved.cshtml
> +    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Syne"/>
Please move these two lines into the `<head>` in the file `Views/Shared/_Layout.cshtml`

2023-11-08 15:53 UTC, TimLeach635 commented on WhaleSpotting/Views/Home/GetInvolved.cshtml
> +    <title>Links website</title>
Remove all of this from this file

2023-11-08 15:53 UTC, TimLeach635 commented on WhaleSpotting/Views/Home/GetInvolved.cshtml
> +</html>
Remove these two lines

2023-11-08 15:53 UTC, TimLeach635 commented on WhaleSpotting/Views/Home/GetInvolved.cshtml
> +  <body class="w3-white">
Remove these lines

2023-11-09 15:12 UTC, AndrewYHuang submitted a review, later dismissed

2023-11-10 08:54 UTC, JackMead approved these changes
Thanks for making those changes - this looks good to go! I've left one comment re a change I suggest we make later, but it might take some configuring so I don't think it's one to block this ticket on 😄

2023-11-10 08:54 UTC, JackMead commented on WhaleSpotting/Views/Home/GetInvolved.cshtml
> +  <style>
It would be nice to move this into its own separate CSS file later to make this file a bit smaller & easier to read, but I suggest that we ignore that for now and raise it as a backlog task!

2023-11-10 11:46 UTC, merged