WS 041 add drop down to new sighting form
TimLeach635/WhaleSpotting-OpenCohort2023 pull request #54
Opened 2023-11-10 13:23 UTC by paulaspinall23

Added dropdown whale selector to new sightings form

2023-11-10 17:16 UTC, JackMead requested changes
Nice work, this looks great! A couple of tiny formatting suggestions and a little bit of context for whoever picks up ws-048 but this should be good to merge on Monday

2023-11-10 17:16 UTC, JackMead commented on WhaleSpotting/wwwroot/css/site.css
> +.button {
Minor, but I can see why this caused you a headache - that's probably a good sign that `button` isn't quite sufficient detail since there are lots of buttons that we definitely don't want this styling to apply to!

Switching this to be `home-page-action-button` or similar might help make it really obvious where & why it's applied, and makes it harder for someone to accidentally see weird large buttons 😄

2023-11-10 17:16 UTC, JackMead commented on WhaleSpotting/Controllers/SightingController.cs
> +            .Where(speciesCheck => speciesCheck.Id == speciesId).First();
Minor, but splitting this over a couple of lines can make it slightly easier to read:
```suggestion
            .Where(speciesCheck => speciesCheck.Id == speciesId)
            .First();
```

2023-11-10 17:16 UTC, JackMead commented on WhaleSpotting/Controllers/SightingController.cs
>          return Ok();
Not really part of your ticket, but this was one of the key bits that Jay was talking about/improving, just to get this sending the user back to a page rather than just showing blank, so it might be a nice bit to fix up here (but if so, check that nobody else is working on `ws-048`
(For example, see [his code here](https://github.com/TimLeach635/WhaleSpotting-OpenCohort2023/blob/ws-048-New-Sighting-Form---Hook-Up-Submit-Button/WhaleSpotting/Controllers/SightingController.cs) and particularly the `return RedirectToAction(...)` command)

2023-11-13 10:35 UTC, AndrewYHuang approved these changes
Looks good to me! :)

2023-11-13 10:35 UTC, merged